- name: nginx install with tls encryption
  hosts: webservers
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
  tasks:
    - name: nginx install
      apt: name=nginx update_cache=yes cache_valid_time=3600
    - name: create directory to tls encryption
      file: path=/etc/nginx/ssl state=directory
    - name: copy tls key
      copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
      notify: nginx restart
    - name: copy tls cert
      copy: src=files/nginx.crt dest={{ cert_file}}
      notify: nginx restart
    - name: copy nginx configuration file
      template: src=templates/nginx.conf.j2 dest={{ conf_file }}
      notify: nginx restart
    - name: configuration
      file: dest=/etc/nginx/sites-enabled/default src={{ conf_file }} state=link
      notify: nginx restart
    - name: copy index.html
      template: src=files/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
  handlers:
    - name: nginx restart
      service: name=nginx state=restarted
